### ISSUE TITLE
'Job Parameter' Field disappears on invalid input

### ISSUE THREAD

**Issue by scout507** [joomla-projects/soc21_website-cronjob#11]
### Steps to reproduce the issue

Tested on this PR: https://github.com/joomla/joomla-cms/pull/35143

1. Go to System -> Cronjobs
2. Add a new Cronjob
3. Select any job type that has 'Job Parameters'
4. Fill out all nessecary fields
5. Fill out at least one field with an invalid input (an already existing name, a character for time interval etc.)
6. Press Save

### Expected result

You should get a warning about your invalid input.

### Actual result

You get the warning but the 'Job Parameters' field is missing afterwards:

**Before saving:**

![Screenshot 2021-08-18 093246](https://user-images.githubusercontent.com/70096457/129856866-cb75c3d4-d6fd-4691-876a-4263aa45c2ea.png)

**After saving:**

![Screenshot 2021-08-18 093500](https://user-images.githubusercontent.com/70096457/129857230-20088e99-727e-46b6-8a35-6b81b9de81d4.png)

### Additional comments

Commented on https://github.com/joomla/joomla-cms/pull/35143#issuecomment-899456771

**Comment by ditsuke** [comment]
Thank you for opening this issue! I'll investigate soon.

**Comment by ditsuke** [comment]
Closed by c73fd27!
